### ISSUE TITLE
Changes to expect with Ignite CLI v0.20.3

### ISSUE THREAD

**Issue by xavierlepretre** [cosmos/sdk-tutorials#1037]
Following up on that, here is a small list of changes between the versions:

---

Non-exhaustive list of the changes when using `v0.20.3`

### Your GUI

- Replace `npm run serve` by `npm run dev`
- Replace `localhost:8080` by `localhost:3000`

### Your first message

List of files modified:

```
modify proto/checkers/tx.proto
modify x/checkers/client/cli/tx.go
create x/checkers/client/cli/tx_create_post.go
modify x/checkers/handler.go
create x/checkers/keeper/msg_server_create_post.go
modify x/checkers/module_simulation.go
create x/checkers/simulation/create_post.go
modify x/checkers/types/codec.go
create x/checkers/types/message_create_post.go
create x/checkers/types/message_create_post_test.go
```

### The stored game object

After scaffolding, this is missing from `x/checkers/types/keys.go`

```go
const (
    StoredGameKey = "StoredGame-value-"
)
```

### Protobuf objects

**`proto/checkers/next_game.proto`**:

The `NextGame` message does not contain a `creator` field:

```protobuf
message NextGame {
  uint64 idValue = 1; 
  
}
```

Someone already found this issue and suggested, for the latest cli version, to use these commands:

<https://github.com/ignite-hq/cli/issues/2234#issuecomment-1083250874>

This changes the order of the fields, however.

**`proto/checkers/genesis.proto`**:

Extra field params in the message

```protobuf
message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  NextGame nextGame = 2;
  repeated StoredGame storedGameList = 3 [(gogoproto.nullable) = false];
  // this line is used by starport scaffolding # genesis/proto/state
}
```

Consequently, the same apply for the generated go struct.

### Files to adjust

Because of the order of the fields differs, initializing the struct must be done with `&NextGame{uint64(0), ""}`.
Or maybe directly with the field names so that the order does not matter: `&NextGame{Creator: "", IdValue: uint64(0)}`

_Originally posted by @julienrbrt in https://github.com/cosmos/sdk-tutorials/pull/945#discussion_r850409332_

**Comment by smsunarto** [comment]
Port should be explicitly defined in config for the Vue app

I haven't checked Vite's implementation, but pretty confident that it has edge cases that can cause the used port to be non-deterministic. For instance, when I run it gives me port 5000 on `npm run serve` when the docs thought it should be `8080`.

Relevant: https://github.com/ignite/cli/issues/2659

**Comment by xavierlepretre** [comment]
It looks like this is referring to obsolete content.
