### ISSUE TITLE
The "Vitalik Buterin on private chains" external article link is incorrect

### ISSUE THREAD

**Issue by jrstrunk** [cosmos/sdk-tutorials#1126]
The "Vitalik Buterin on private chains" external link at the bottom of the [IDA Week 0 Public and Managed Blockchains](https://interchainacademy.cosmos.network/academy/0.0-B9lab-Blockchains/3_managed.html) page is incorrect and instead links to an article titled "Three (non-pointless) permissioned blockchains in production." I would submit a contribution to fix this myself instead of opening a blank issue, but I am not sure what the original link was supposed to be as it is not referenced anywhere else in the repository.

**Comment by xavierlepretre** [comment]
The link is now fixed.
