### ISSUE TITLE
Create a `x/gov` tutorial 

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/sdk-tutorials#1135]
Create a `x/gov` tutorial about the new possibilities with the `gov` module from `0.46`+

- [x] Give an example of both a legacy proposal and a new-style proposal

**Comment by nooomski** [comment]
I think we can get started on this without an answer on the metadata story in https://github.com/cosmos/cosmos-sdk/issues/11301
Just mention there are metadata standards for the JSON upload, and we can then amend the tutorial once we have them.

@marbar3778 could you find a spot on the SDK project board?

**Comment by glnro** [comment]
Fwiw [this test](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_test.go#L106) demonstrates the use of both legacy and the new gov proposal execution in a single use case/story.
