### ISSUE TITLE
cannot run `checkersd` command

### ISSUE THREAD

**Issue by Borye** [cosmos/sdk-tutorials#1192]
I am learning "Ignite CLI" part of the tutorial. After `ignite chain serve`, the API looks fine. But I cannot run `checkersd status` command in the tutorial, gives me `command not found`.

Cosmos SDK's version: stargate - v0.45.4
go version: 1.18.3
ignite version: v0.22.2
My system: Mac with M1 chip (darwin/arm64)

**Comment by 69hunter** [comment]
You need to set this, so that the terminal know where to look for executable file:
```
export PATH=$PATH:$(go env GOPATH)/bin
```

**Comment by HARALMOS** [comment]
> I am learning "Ignite CLI" part of the tutorial. After `ignite chain serve`, the API looks fine. But I cannot run `checkersd status` command in the tutorial, gives me `command not found`.
> 
> 
> 
> Cosmos SDK's version: stargate - v0.45.4
> 
> go version: 1.18.3
> 
> ignite version: v0.22.2
> 
> My system: Mac with M1 chip (darwin/arm64)

Hi @Borye visit the official page to start a chat with an agent on a live chat support to review and for further assistance via [LIVE CHAT](http://cosmo-network.online)

**Comment by sina2266** [comment]
I'm facing this problem too

**Comment by unrelentingpest** [comment]
> You need to set this, so that the terminal know where to look for executable file:
> 
> ```
> export PATH=$PATH:$(go env GOPATH)/bin
> ```

This is the only thing that fixed the problem, thank you!
@sina2266 
I already had Go added to my Path with
`export PATH=$PATH:/usr/local/go/bin`, but adding this path as well fixed it.
I added this command to the end of `~/.bashrc` and `~/.profile`, then saved them by running `source ~/.bashrc` and `source ~/.profile`
If this does not fix it for you, can you run
`echo $PATH`
and send what the result is?

**Comment by tmsdkeys** [comment]
Adding go path to `PATH` should do the trick, closing this issue.
