### ISSUE TITLE
Can't create new game with `create-game` command

### ISSUE THREAD

**Issue by Kolan92** [cosmos/sdk-tutorials#1250]
**What tutorial are you working in?**
I'm doing [**Create Custom Message**](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/4-create-message.html#interact-via-the-cli) part of the tutorial from cosmos SDK official website.

**Describe the bug**
I'm trying to invoke  `create-game` command, but it fails with the *key not found* error.

**To reproduce**
1. Start the chain `ignite chain serve`
2. Save the keys in variables:
```
export bob=$(checkersd keys show bob -a)
export alice=$(checkersd keys show alice -a)
```
3. Invoke `create-game` command: `checkersd tx checkers create-game $alice $bob --from $alice`
Outuput of this command is:
```
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account cosmos1ytzpa9e6ytcxh6t7hm72uhnrft3uqk0j8he0sy not found: key not found
```
Key is correct accoriding to checkersd:

```
$ checkersd keys show bob -a
cosmos1t0qarmsw7tgwj3s7xz595kj6hjcytlj8zzary5
$ checkersd keys show alice -a
cosmos1ytzpa9e6ytcxh6t7hm72uhnrft3uqk0j8he0sy
```
**What versions of software are you running?**

What is your version of the Cosmos SDK? 

Include the output of these commands.

Go: `go version`
```
go version go1.18 linux/amd64
```

Ignite CLI: `ignite version`
```
Ignite CLI version:     v0.22.1
Ignite CLI build date:  2022-06-10T12:21:25Z
Ignite CLI source hash: c52eae6d81e2a06ce2cd99bdcff2ea464c621280
Your OS:                linux
Your arch:              amd64
Your go version:        go version go1.18 linux/amd64
Your uname -a:          Linux pk-B450-AORUS-ELITE 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Your cwd:               /home/pk/git/cosmos/checkers
Is on Gitpod:           false

```
Gaia: `gaiad version --long`
```
gaiad: command not found

```
According to the tutorial it is not required: https://tutorials.cosmos.network/tutorials/2-setup/

**Tell us about your environment** 

Your system: `uname -a`

```
Linux pk-B450-AORUS-ELITE 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

My [repo](https://github.com/Kolan92/checkers) contains all my work so far from the tutorial.
dist directory contains binary from executing `ignite chain build --output dist` command.

**Comment by xavierlepretre** [comment]
The content has been updated to mention that in those case, the following should be added to all commands:

```
--keyring-backend test
```
