### ISSUE TITLE
Need Guide for adding validators

### ISSUE THREAD

**Issue by amitkarpe** [cosmos/sdk-tutorials#1260]
Hi,
There should be a clear guide with instructions for adding validators/nodes.

https://github.com/cosmos/sdk-tutorials/blob/master/tutorials/3-run-node/index.md

Specifically looking for steps to create validators/nodes after genesis. How to build multi node blockchain on Virtual Machines?

**Comment by xavierlepretre** [comment]
The hands-on-exercise [does that](https://github.com/cosmos/sdk-tutorials/blob/master/hands-on-exercise/4-run-in-prod/1-run-prod-docker.md). Doing it after genesis is very similar, but could indeed be added at some point.
