### ISSUE TITLE
Add content around capabilities used in IBC context

### ISSUE THREAD

**Issue by tmsdkeys** [cosmos/sdk-tutorials#1277]
In IBC, capabilities are used to ensure that an IBC application does not send packets on channels/ports is does not have the capability for. This is something that is scarcely documented at the moment and we could add more info (practical, scoped to what is useful for an IBC application dev) about it.

**Solution**: Make a transcript based on a capabilities deep dive recently recorded by one of ibc-go's core engineers.

**Comment by xavierlepretre** [comment]
@murataniloener Opinion?

**Comment by coldice** [comment]
Moved to https://github.com/cosmos/developer-portal/issues/17
