### ISSUE TITLE
A guide on creating a cosmos application without Ignite

### ISSUE THREAD

**Issue by JasperSurmont** [cosmos/sdk-tutorials#1353]
**Is your feature request related to a problem? Please describe.**

Not a problem per se. To get a better understanding of Cosmos SDK I'd like to build a chain without using Ignite. The example Simapp is the closest to what I can find, but it is a bit bloated: I would like to create a chain with no (or minimal) other modules. 

**Describe the solution you'd like to see**

Perhaps a tutorial or explanation of the requirements that a cosmos chain need to function properly. I know about all the basics of cosmos, but I don't know which elements are necessary or what the purpose is of a lot of the SimApp's code

**Describe alternatives you've considered**

N/A

**Comment by tmsdkeys** [comment]
Thanks for your suggestion @JasperSurmont . It's a valid remark and something that is on our roadmap in terms of creating/adding some content (or at the very least redirecting to external content) about building Cosmos SDK chains without using Ignite CLI. 

Can't promise an immediate ETA but we are aware of the need

**Comment by xavierlepretre** [comment]
Still on the roadmap. Closing this issue as the content moves to [new repo](https://github.com/cosmos/developer-portal/).
