### ISSUE TITLE
Explain how to extend existing keepers and handlers

### ISSUE THREAD

**Issue by fedekunze** [cosmos/sdk-tutorials#139]
Add documentation or update the tutorial to explain how to extend existing keepers and handlers.

Ref: https://github.com/cosmos/cosmos-sdk/issues/4664

**Comment by gamarin2** [comment]
I can add a small doc about that in the `building-modules`  section

**Comment by gamarin2** [comment]
I started writing the doc but I realized it would fit better in the tutorial than in the reference.

**Comment by xavierlepretre** [comment]
Is this still to be added?
