### ISSUE TITLE
Chain spelled "Shain" in IgniteCLI tutorial

### ISSUE THREAD

**Issue by noslav** [cosmos/sdk-tutorials#1392]
Thank you for helping us improve the Cosmos Developer Portal. 

Use this form to submit a bug report for the Developer Portal in general (broken link, missing content, navigation, and so on). 

To submit a bug report for a specific tutorial, use [Cosmos SDK tutorials bug report](tutorials-bug-report.md).

**What is the specific Developer Portal page?**
Paste the URL here.

https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/8-game-winner.html

**Describe the bug**
Describe the bug. Tell us about your challenges. A clear and concise description helps us identify and understand the issue. Take a screen capture if that helps. 
<img width="1127" alt="Screen Shot 2023-05-25 at 18 59 19" src="https://github.com/cosmos/sdk-tutorials/assets/26611201/59eaadc7-1ce6-43d9-afa5-be7abb97215e">

**To reproduce**
Steps to reproduce the issue:
1. 

**Solution**
Do you have a solution? Great. Describe it here or even better, see [CONTRIBUTING.md](https://github.com/cosmos/sdk-tutorials/blob/master/CONTRIBUTING.md) and make a direct contribution. Feel free to submit a PR.

**Comment by xavierlepretre** [comment]
@noslav What is this here?
