### ISSUE TITLE
asses pr to upstream 

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/sdk-tutorials#1403]
asses https://github.com/cosmos/sdk-tutorials/pull/1078/files#diff-e1b21568812267c6f30ded3f0eccc55d11732bbc63faaefed07e4ae5c2779a09 in order to upstream needed data

**Comment by xavierlepretre** [comment]
Not sure what this refers to.

**Comment by coldice** [comment]
Moved to https://github.com/cosmos/developer-portal/issues/17

**Comment by coldice** [comment]
For the dev portal, the changes have been moved over ✔️
