### ISSUE TITLE
getting error "Could not resolve name - jack.id" in SDK-Tutorial

### ISSUE THREAD

**Issue by astro79** [cosmos/sdk-tutorials#152]
## Summary of Bug

I'm trying to run nameservice CLI application  as per the instructions in the tutorial (https://cosmos.network/docs/tutorial/build-run.html#building-the-nameservice-application).

After running the "nscli query nameservice resolve jack.id", I'm getting below error:
"Could not resolve name - jack.id"

## Version

github.com/cosmos/cosmos-sdk v0.28.2-0.20190616100639-18415eedaf25 h1:BbhcH/+GrA/j/6LimGGGq7BuMtmVF9nfk2HrCjevktw=
github.com/cosmos/cosmos-sdk v0.28.2-0.20190616100639-18415eedaf25/go.mod h1:MvaJDmjgAK7X1rTnpk8+c6tUFfIZ++iuNCp2sUWzprM=
github.com/cosmos/cosmos-sdk v0.28.2-0.20190718000257-257d3bfbf2d0 h1:lKp7Z01zQDrmjz6V0QkvQ0Lsql/I+yspTnKu1aHgKOo=
github.com/cosmos/cosmos-sdk v0.28.2-0.20190718000257-257d3bfbf2d0/go.mod h1:UV765S3m9sxCg8rYaBr4XgeHZl2UP6y++Coz9mLlYFc=
github.com/cosmos/cosmos-sdk v0.35.0 h1:EPeie1aKHwnXtTzKggvabG7aAPN+DDmju2xquvjFwao=
github.com/cosmos/cosmos-sdk v0.35.0/go.mod h1:ruF+G4D7hRf34uzZQvf/SIja9fsIThU5D7GirwTMQ9I=
github.com/cosmos/cosmos-sdk v0.36.0-rc1 h1:hgSXNeVwNYxD0+O9DxRrxJcir9Z7Q5zreLV6G7GrjYA=
github.com/cosmos/cosmos-sdk v0.36.0-rc1/go.mod h1:UV765S3m9sxCg8rYaBr4XgeHZl2UP6y++Coz9mLlYFc=
github.com/cosmos/cosmos-sdk v0.36.0 h1:nDHhZDeucmv/PoThz89Q8cj9S8OH2EUutgertz2pZ90=
github.com/cosmos/cosmos-sdk v0.37.0-rc1 h1:DjrmTg+MTRJozgqIhI+7vT1MI2hQobeb8AQcXQ87JO0=
github.com/cosmos/cosmos-sdk v0.37.0-rc1/go.mod h1:3b/k/Zd+YDuttSmEJdNkxga1H5EIiDUhSYeErAHQN7A=
github.com/cosmos/cosmos-sdk v0.37.0 h1:S2I3NDGN2wqfGlY5KqkAHTpfezjhgeqDxrCxhlhd528=
github.com/cosmos/cosmos-sdk v0.37.0/go.mod h1:3b/k/Zd+YDuttSmEJdNkxga1H5EIiDUhSYeErAHQN7A=

## Steps to Reproduce

run commands as per the instructions on this page:
https://cosmos.network/docs/tutorial/build-run.html#building-the-nameservice-application
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I wasn't able to replicate your issue when I ran through the commands, could you update to master and try again

**Comment by astro79** [comment]
I updated the repo, and then it worked ! Thanks for your help and support !

Thanks,
Hiren.
