### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by marbar3778** [cosmos/sdk-tutorials#156]
- [ ] Korean
- [ ] update chinese
- [ ] spanish
- [ ] russian

**Comment by yanicka** [comment]
I would like to translate it into russian.

**Comment by marbar3778** [comment]
we would love this contribution, thank you

**Comment by MiryangJung** [comment]
I would like to translate it into korean. Is it Ok?

**Comment by marbar3778** [comment]
> I would like to translate it into korean. Is it Ok?

yes that would be amazing!! thank you so much

**Comment by emanoelopes** [comment]
Portuguese-BR, ok?

**Comment by HwaGyeong** [comment]
Hello i would like to translate to korean is it finished??

**Comment by kye199** [comment]
can you make po file?

**Comment by MiryangJung** [comment]
> Hello i would like to translate to korean is it finished??

Hello! I'll send pr tomorrow.  I work little front part . I think it'd be nice if you could do it after my progress.

**Comment by hschoenburg** [comment]
> Portuguese-BR, ok?

of course that would be amazing thanks

**Comment by marbar3778** [comment]
closing this issue as this was mainly opened for hacktoberfest
