### ISSUE TITLE
Tutorial missing hccli (used on one page but not created)

### ISSUE THREAD

**Issue by alexkogon** [cosmos/sdk-tutorials#196]
Hi,

I'm following your basic tutorial and on:

https://github.com/cosmos/sdk-tutorials/blob/master/hellochain/tutorial/04-try-it-out.md

it says I should try both hcd and hccli but on:

https://github.com/cosmos/sdk-tutorials/blob/master/hellochain/tutorial/02-simple-start.md

it only includes the code for hcd so hccli is not working when I get to step 4 (unless I'm missing something)

Thanks

**Comment by Twizzes** [comment]
I had the same issue.

I just copied and pasted the code from here:

https://github.com/cosmos/sdk-tutorials/blob/master/hellochain/cmd/hccli/main.go

into `cmd/hccli/main.go `

And then I change the makefile to this:

``` Makefile
install: go.sum
	go install $(BUILD_FLAGS) ./cmd/hcd
	go install $(BUILD_FLAGS) ./cmd/hccli
```

and then ran `make install` and `go install` and it worked
