### ISSUE TITLE
not engouh arguments

### ISSUE THREAD

**Issue by hot3246624** [cosmos/sdk-tutorials#202]
When i perform make install, there are two baffling errors as below, what is the matter?

=======================
./app.go:155:36: not enough arguments in call to staking.NewKeeper
	have (*amino.Codec, *"github.com/cosmos/cosmos-sdk/store/types".KVStoreKey, "github.com/cosmos/cosmos-sdk/x/supply/internal/keeper".Keeper, subspace.Subspace, "github.com/cosmos/cosmos-sdk/types".CodespaceType)
	want (*amino.Codec, "github.com/cosmos/cosmos-sdk/store/types".StoreKey, "github.com/cosmos/cosmos-sdk/store/types".StoreKey, "github.com/cosmos/cosmos-sdk/x/staking/types".SupplyKeeper, subspace.Subspace, "github.com/cosmos/cosmos-sdk/types".CodespaceType)
./app.go:207:23: not enough arguments in call to staking.NewAppModule
	have ("github.com/cosmos/cosmos-sdk/x/staking/keeper".Keeper, auth.AccountKeeper, "github.com/cosmos/cosmos-sdk/x/supply/internal/keeper".Keeper)
	want ("github.com/cosmos/cosmos-sdk/x/staking/keeper".Keeper, "github.com/cosmos/cosmos-sdk/x/staking/types".DistributionKeeper, "github.com/cosmos/cosmos-sdk/x/staking/types".AccountKeeper, "github.com/cosmos/cosmos-sdk/x/staking/types".SupplyKeeper)

**Comment by marbar3778** [comment]
what version of the cosmos-sdk are you using?

**Comment by hot3246624** [comment]
github.com/cosmos/cosmos-sdk v0.37.4
