### ISSUE TITLE
Is there any way to change bond_denom

### ISSUE THREAD

**Issue by victorrica** [cosmos/sdk-tutorials#208]
I'm trying to change bond denom. Is there any best practice to do it?

**Comment by marbar3778** [comment]
Once the genesis is generated you have to edit the genesis file. You can use jq to speed things up

**Comment by victorrica** [comment]
> Once the genesis is generated you have to edit the genesis file. You can use jq to speed things up
> 
> here is also a issue that described the samething: #168

This works! Thx.
