### ISSUE TITLE
Create own token name in HelloChain tutorial

### ISSUE THREAD

**Issue by shikharfb** [cosmos/sdk-tutorials#210]
How to change the name of `hellotoken` and `stake` token names in Hello Chain tutorial, or after we scaffold the application for HelloChain?

I tried changing the name in `genesis.json` before starting the chain, but after that when i do any transaction with `mytoken` (new token name), it says `ERROR: invalid coin expression: 5000mytoken`

**Comment by shikhardb** [comment]
@marbar3778  Any help on this?

**Comment by marbar3778** [comment]
not sure what would be different than https://github.com/cosmos/sdk-tutorials/issues/168 but will look into it, I haven't worked much with hellochain so will need a bit to debug. will get back to you

**Comment by shikhardb** [comment]
Thanks 😄

**Comment by marbar3778** [comment]
@hschoenburg could you look at this issue when you are updating the tutorial as well. not sure how it is different
