### ISSUE TITLE
hellochain can not query

### ISSUE THREAD

**Issue by jerryma0912** [cosmos/sdk-tutorials#212]
hello, I run the hellochain in my local computer, but I encountered a problem as follows.
-----------
Operation process：
1.create "alice" account and its address is "cosmos1twhnqe0ypjyd09sfkjz3paajlrh828grfhk6z5"
2.create "bob" account and its address is "cosmos1mqf00lkrhu4ca7kyn6gyh4dcg27urxx39qarz7"
3.alice use command "hccli tx greeter say hellom cosmos1mqf00lkrhu4ca7kyn6gyh4dcg27urxx39qarz7 --from alice --chain-id test-chain-zccezZ" to say hello to bob. blockchain access this transaction.
----------
Error process:
I use command "hccli query greeter list cosmos1twhnqe0ypjyd09sfkjz3paajlrh828grfhk6z5 --chain-id test-chain-zccezZ" to query the recording, but hcd daemon says ERROR as follows.

E[2020-01-02|23:10:27.505] Panic in RPC HTTP handler                    module=rpc-server err="unmarshal to types.Greeting failed after 56 bytes (encountered fieldnNum: 1, but we have already seen fnum: 1\nbytes:0A360A145BAF3065E40C88D79609B48510F7B2F8EE751D031214D812F7FEC3BF2B8EFAC49E904BD5B842BDC198D11A0868656C6C6F6D646A): 0A360A145BAF3065E40C88D79609B48510F7B2F8EE751D031214D812F7FEC3BF2B8EFAC49E904BD5B842BDC198D11A0868656C6C6F6D646A0A360A145BAF3065E40C88D79609B48510F7B2F8EE751D031214D812F7FEC3BF2B8EFAC49E904BD5B842BDC198D11A0868656C6C6F6D646A" stack="goroutine 79 [running]:\nruntime/debug.Stack(0xc000c57be8, 0x1b2ab40, 0xc003193d30)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc000b36500, 0x1ffd840, 0xc00016caa0, 0xbf7b9fd8de19db38, 0x1bd910f52, 0x27b4c60, 0xc000bf6000)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/lib/server/http_server.go:161 +0x486\npanic(0x1b2ab40, 0xc003193d30)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/tendermint/go-amino.(*Codec).MustUnmarshalBinaryBare(...)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/go-amino@v0.15.0/amino.go:358\nawesomeProject/x/greeter/internal/keeper.listGreetings(0x1ffcf00, 0xc0000d0000, 0x200c740, 0xc000043880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/jerry/Desktop/awesomeProject/x/greeter/internal/keeper/querier.go:40 +0x5bd\nawesomeProject/x/greeter/internal/keeper.NewQuerier.func1(0x1ffcf00, 0xc0000d0000, 0x200c740, 0xc000043880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/jerry/Desktop/awesomeProject/x/greeter/internal/keeper/querier.go:21 +0x19e\ngithub.com/cosmos/cosmos-sdk/baseapp.handleQueryCustom(0xc0000e8b40, 0xc000043840, 0x4, 0x4, 0x27d1fa0, 0x0, 0x0, 0xc00316dc20, 0x41, 0x2b6, ...)\n\t/Users/jerry/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/baseapp/baseapp.go:609 +0x5c9\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0000e8b40, 0x27d1fa0, 0x0, 0x0, 0xc00316dc20, 0x41, 0x0, 0x1, 0x0, 0x0, ...)\n\t/Users/jerry/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/baseapp/baseapp.go:471 +0x2e8\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc0000b5740, 0x27d1fa0, 0x0, 0x0, 0xc00316dc20, 0x41, 0x0, 0x1, 0x0, 0x0, ...)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/abci/client/local_client.go:207 +0x10e\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0xc000c71060, 0x27d1fa0, 0x0, 0x0, 0xc00316dc20, 0x41, 0x0, 0x1, 0x0, 0x0, ...)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/proxy/app_conn.go:143 +0x6a\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0xc000b365c0, 0xc00316dc20, 0x41, 0x27d1fa0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/core/abci.go:57 +0x114\nreflect.Value.call(0x1b58600, 0x1e8db70, 0x13, 0x1c96d18, 0x4, 0xc0008e0a80, 0x5, 0x5, 0x5, 0x18, ...)\n\t/usr/local/go/src/reflect/value.go:460 +0x5f6\nreflect.Value.Call(0x1b58600, 0x1e8db70, 0x13, 0xc0008e0a80, 0x5, 0x5, 0x4, 0x4, 0x0)\n\t/usr/local/go/src/reflect/value.go:321 +0xb4\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x1ff8780, 0xc000b36500, 0xc000bf6000)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/lib/server/handlers.go:158 +0x944\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x1ff8780, 0xc000b36500, 0xc000bf6000)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/lib/server/handlers.go:182 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc000c19000, 0x1ff8780, 0xc000b36500, 0xc000bf6000)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc0000b3ec0, 0x1ff8780, 0xc000b36500, 0xc000bf6000)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1fe0ca0, 0xc0000b3ec0, 0xf4240, 0x1ff8780, 0xc000b36500, 0xc000bf6000)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/lib/server/http_server.go:206 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1ff8e80, 0xc000a0c0e0, 0xc000bf6000)\n\t/Users/jerry/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/rpc/lib/server/http_server.go:179 +0x33f\nnet/http.HandlerFunc.ServeHTTP(0xc0009e8000, 0x1ff8e80, 0xc000a0c0e0, 0xc000bf6000)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.serverHandler.ServeHTTP(0xc000a0c000, 0x1ff8e80, 0xc000a0c0e0, 0xc000bf6000)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc000b12c80, 0x1ffcec0, 0xc000043600)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2928 +0x384\n"

--------
Can you tell me why it happens and how to resolve this problem? Thank you!

**Comment by marbar3778** [comment]
I found the error, the codec was not registered correctly, I will notify the author of the tutorial to make edits @hschoenburg

**Comment by jerryma0912** [comment]
thanks, I hope the problem can be solved as soon as possible @marbar3778
