### ISSUE TITLE
nameservice export genesis

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#216]
apparently some kind of error in nameservice export genesis. It results in an error about not being able to unmarshall empty bytes. furthermore the nameservice validate genesis functions throws an error if a name contains an empty value. this should not be a error as a name with an empty value should be no problem.

**Comment by okwme** [comment]
export genesis exports names as values and values as names (or import switches them.... either way they're WRONG)

**Comment by xavierlepretre** [comment]
This refers to obsolete content.
