### ISSUE TITLE
--minimum-gas-prices is allowing transaction with empty fees

### ISSUE THREAD

**Issue by Twizzes** [cosmos/sdk-tutorials#218]
## Summary of Bug

I have pulled the latest version of cosmos/sdk-tutorial and installed the nameservice daemon and cli, as well as gaia daemon and cli.

EXPECTED:
When I start a node with `gaid start --minimum-gas-prices=...` then I can't make send transactions without specifying a gas price or fee amount. This is working correctly for gaia.

ACTUAL:
When I run `nsd start --minimum-gas-prices=...` then I can make send transactions without specifying either fees or gasprices flag. No fees are charged and the transaction goes through.

Am I missing something? I tried to compare the two source codes, and couldn't see anything different that would cause this.

## Version

```
module github.com/cosmos/sdk-tutorials/nameservice

go 1.13

require (
	github.com/cosmos/cosmos-sdk v0.37.5
	github.com/gorilla/mux v1.7.3
	github.com/spf13/cobra v0.0.5
	github.com/spf13/viper v1.6.1
	github.com/stretchr/testify v1.4.0
	github.com/tendermint/go-amino v0.15.1
	github.com/tendermint/tendermint v0.32.8
	github.com/tendermint/tm-db v0.2.0
)
```

## Steps to Reproduce

- Pull latest cosmos/sdk-tutorials repo and install nscli and nsd
- ```
  nsd init nsnode --chain-id nschain
  nscli keys add a1
  nscli keys add a2
  nsd add-genesis-account a1 100000000stake,1000nametoken
  nsd gentx --name a1  
  nsd collect-gentxs
  nsd start --minimum-gas-prices=0.00001nametoken
  ```
- In a new shell:
  ```
  nscli tx send $(nscli keys show a1 -a) $(nscli keys show a2 -a) 1nametoken --broadcast-mode block --chain-id nschain
  ```
- **Notice that the transaction goes through successfully. No fees are charged.**
- Relevant output when querying for the transaction:
  ``` 
  nscli query tx <txhash> --trust-node
  ...
  info: ""
  gaswanted: 200000
  gasused: 25231
  codespace: ""
  tx:
    msg:
    - from_address: cosmos19z38g6lgjkh9mjyly852havakqphw9yxjx0mdu
      to_address: cosmos1ld79yj7rdpysl8zrhn2je2sf76a50nswl6fq3y
      amount:
      - denom: nametoken
        amount: "1"
    fee:
      amount: []
      gas: 200000
  ...
  ```
- When specifying a gas-price for a transaction, the correct action is taken:
  ```
  nscli tx send $(nscli keys show a1 -a) $(nscli keys show a2 -a) 1nametoken --broadcast-mode block --chain-id nschain --gas-prices 0.1nametoken
  ...
  rawlog: '{"codespace":"sdk","code":5,"message":"insufficient funds to pay for fees;
  999nametoken < 20000nametoken"}'
  ...
  ```
  ```
  nscli tx send $(nscli keys show a1 -a) $(nscli keys show a2 -a) 1nametoken --broadcast-mode block --chain-id nschain --gas-prices 0.0001nametoken
  ...
  nscli query tx <latest success tx hash> --trust-node
  ...
  gaswanted: 200000
  gasused: 38179
  codespace: ""
  tx:
    msg:
    - from_address: cosmos19z38g6lgjkh9mjyly852havakqphw9yxjx0mdu
      to_address: cosmos1ld79yj7rdpysl8zrhn2je2sf76a50nswl6fq3y
      amount:
      - denom: nametoken
        amount: "1"
    fee:
      amount:
      - denom: nametoken
        amount: "20"
      gas: 200000
  ```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks @Twizzes. Would you like to submit a PR?
