### ISSUE TITLE
Consider Getting Serious

### ISSUE THREAD

**Issue by lazaridiscom** [cosmos/sdk-tutorials#223]
"Hurrah you are now a blockchain engineer!"

and some  'astro-bird':

https://tutorials.cosmos.network/hellochain/tutorial/16-complete.html

## Expected

Serious, concise tenor.

**Comment by marbar3778** [comment]
Did you find this tutorial too easy? or is the wording not that serious in your opinion?

**Comment by lazaridiscom** [comment]
> Did you find this tutorial too easy?

being "easy" is fine, though I did not yet went through the tutorial fully.

> or is the wording not that serious in your opinion?

yes, the wording. Tutorials should be straight to the point, avoid jokes and fun-graphics etc, avoid "patronizing" tone etc.

See the Hyperledger project as a reference, or e.g. Semiconductor Documentation - usually highest quality, because they address engineers/engineer-minded  that need to focus and become productive very fast.

## Possible Solution

You could provide an additional tutorial like "cosmobird", which implements a very very simple game. This could be kept in a more casual tone (again, not too casual/jokingly).

## Spawning Issue

=> Provide Documentation Requirements and Guidelines

**Comment by hschoenburg** [comment]
Consider lightening up? This sis a "hello world" tutorial. It is intended to be approachable easy and fun.
