### ISSUE TITLE
Update Repository Description and URL

### ISSUE THREAD

**Issue by lazaridiscom** [cosmos/sdk-tutorials#227]
Missing URL: https://tutorials.cosmos.network/

Description could become like **"Cosmos SDK Tutorial Website and Code"**

**Comment by lazaridiscom** [comment]
Example here: https://github.com/lazaridiscom/sdk-tutorials

**Comment by hschoenburg** [comment]
fixed

**Comment by lazaridiscom** [comment]
Description still reads: "A tutorial for building modules for the Cosmos SDK", which seems wrong.

**Comment by marbar3778** [comment]
fixed it, i have permission to do this now.

**Comment by lazaridiscom** [comment]
This repository contains:
* The Cosmos SDK Tutorials Website
* The Tuturials Code

Thus, the description you gave it is not precisely describing it (and this "for building modules" confuses me personally a bit).

So, you should reopen this issue, possibly someone comes up with the final description.
