### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by lazaridiscom** [cosmos/sdk-tutorials#228]
The tutorials on 

https://tutorials.cosmos.network/hellochain/tutorial/00-intro.html

contain `Makefiles` and `.sh` scripts.

Either make them cross-platform, or document status re windows.

**Comment by marbar3778** [comment]
will add how to install make on windows to the tutorial, for the time being here is a simple guide on how to do it: https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows#32127632

**Comment by lazaridiscom** [comment]
https://chocolatey.org/instal
`choco install make`

**Comment by alexanderbez** [comment]
We don't really claim or test support for windows anywhere.

**Comment by lazaridiscom** [comment]
The tutorial-site is an entry-point, so you need to clarify the windows status (e.g. you can't ignore the existence of Windows).

Personally, I believe that supporting Windows (native, not via virtual machines) leads to a better (overall cross-platform) design.

**Comment by lazaridiscom** [comment]
WSL seems to work fine, see #238

**Comment by lazaridiscom** [comment]
> or document status re windows.

done within #238: clarifies Windows situation (telling users to use a virtual machine or WSL).

Closing.
