### ISSUE TITLE
Add info to scavenge tutorial when make install fails

### ISSUE THREAD

**Issue by ManuStoessel** [cosmos/sdk-tutorials#231]
**What happened:**

I ran `make install` and it failed like so:

```bash
 ~/godays2020/workshop/scaffold   master  make install
/bin/sh: go-bindata: Kommando nicht gefunden.
make: *** [Makefile:13: generate] Fehler 127
```

**Solution:**

Run `make` because this will include the step `make tools` to install `go-bindata`.

So it would be great to add this info to the tutorial in sdk-tutorials/scavenge/tutorial/03-scaffold.md

**Comment by marbar3778** [comment]
thank you, i will make the needed adjustments
