### ISSUE TITLE
Scavenge tutorial fixes

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#233]
* `MsgCommitSolution.go` missing
* combing `cd scavenge` with `cd x`
* vuepress link from keeper to handler doesn't work (link looks correct tho)
* Better to use VI
* tell user to make new working directory outside of `/scaffold` (!!!)
* app page should have make file instead of main.go twice
* Use phony on all targets
* Maybe change `make install` to `make` on run page
* typo on last section of run.md (`scavngD` => `scavengeD`)

**Comment by lazaridiscom** [comment]
Please consider additionally this one:
* add `00-intro.md`and link to it from main readme.

This is to be consistent with the other tutorials.

**Comment by okwme** [comment]
Thanks for the suggestion @lazaridiscom but I don't see the benefit in creating a new intro document when the background file suffices and users should never need to encounter the numbering system.

If you felt like renaming all the files and references to the files so that `01-background.md` became `00-background.md` or `00-intro.md` I wouldn't stop you but I wouldn't blame you if you had better things to do with your time.

**Comment by lazaridiscom** [comment]
Oh my...
