### ISSUE TITLE
Tendermint has changed directory paths and this breaks hellochain/starter

### ISSUE THREAD

**Issue by EVSmithFetchAI** [cosmos/sdk-tutorials#237]
The package tendermint/libs/common does not exist any more: see PR here: https://github.com/tendermint/tendermint/pull/4240. But tendermint/libs/common is imported in several places in hellochain/starter, so starter can no longer be imported which breaks the hellochain tutorial. Running `make install` in the hellochain tutorial gives the error: 
> build github.com/EVSmithFetchAI/hellochain/cmd/hcd: cannot load github.com/tendermint/tendermint/libs/common: module github.com/tendermint/tendermint@latest found (v0.33.0), but does not contain package github.com/tendermint/tendermint/libs/common`

I'm very new to both cosmos and go, so let me know if I've misunderstood something!

**Comment by marbar3778** [comment]
hey the tutorials have no been updated to 0.33 of tendermint since the sdk release with it has not been cut. If you are using the same go.mod that is in the tutorial then this will not be a problem
```
	github.com/cosmos/cosmos-sdk v0.37.3
	github.com/gorilla/mux v1.7.0
	github.com/mattn/go-isatty v0.0.8 // indirect
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/pelletier/go-toml v1.4.0 // indirect
	github.com/prometheus/client_golang v0.9.4 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cobra v0.0.5
	github.com/spf13/viper v1.4.0
	github.com/tendermint/go-amino v0.15.0
	github.com/tendermint/tendermint v0.32.6
	github.com/tendermint/tm-db v0.2.0
	golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586 // indirect
	golang.org/x/net v0.0.0-20190813141303-74dc4d7220e7 // indirect
	golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/genproto v0.0.0-20190611190212-a7e196e89fd3 // indirect
```

**Comment by marbar3778** [comment]
hey the tutorials have no been updated to 0.33 of tendermint since the sdk release with it has not been cut. If you are using the same go.mod that is in the tutorial then this will not be a problem

**Comment by EVSmithFetchAI** [comment]
Thanks for your reply - problem solved! I generated my go.mod by running `go mod init`, which produced `go.mod` with tendermint v0.33.0. I changed this to v0.32.6 and now `make install` runs successfully.
