### ISSUE TITLE
Tendermint RPC calls are still not available

### ISSUE THREAD

**Issue by tuckermint** [cosmos/sdk-tutorials#246]
Follow up to #131 

I made a new chain based on the newly merged nameservice code.
I still don't see node_info as an available rpc call.

Here is what I see at http://127.0.0.1:26657/:

`
Available endpoints:

Endpoints that require arguments:
//127.0.0.1:26657/abci_info?
//127.0.0.1:26657/abci_query?path=_&data=_&height=_&prove=_
//127.0.0.1:26657/block?height=_
//127.0.0.1:26657/block_by_hash?hash=_
//127.0.0.1:26657/block_results?height=_
//127.0.0.1:26657/blockchain?minHeight=_&maxHeight=_
//127.0.0.1:26657/broadcast_evidence?evidence=_
//127.0.0.1:26657/broadcast_tx_async?tx=_
//127.0.0.1:26657/broadcast_tx_commit?tx=_
//127.0.0.1:26657/broadcast_tx_sync?tx=_
//127.0.0.1:26657/commit?height=_
//127.0.0.1:26657/consensus_params?height=_
//127.0.0.1:26657/consensus_state?
//127.0.0.1:26657/dump_consensus_state?
//127.0.0.1:26657/genesis?
//127.0.0.1:26657/health?
//127.0.0.1:26657/net_info?
//127.0.0.1:26657/num_unconfirmed_txs?
//127.0.0.1:26657/status?
//127.0.0.1:26657/subscribe?query=_
//127.0.0.1:26657/tx?hash=_&prove=_
//127.0.0.1:26657/tx_search?query=_&prove=_&page=_&per_page=_
//127.0.0.1:26657/unconfirmed_txs?limit=_
//127.0.0.1:26657/unsubscribe?query=_
//127.0.0.1:26657/unsubscribe_all?
//127.0.0.1:26657/validators?height=_&page=_&per_page=_
`

Thanks 
@marbar3778

**Comment by marbar3778** [comment]
node_info is a cosmos-sdk route, here is a better representation of the routes for tendermint: https://docs.tendermint.com/master/rpc/.

you might be looking for https://docs.tendermint.com/master/rpc/#/Info/net_info

**Comment by tuckermint** [comment]
I'm trying to make a custom chain work with MathWallet.
MathWallet makes a GET request to http://127.0.0.1:26657/node_info which fails.

This repo is a tutorial for cosmos-sdk, so why would it be missing the cosmos routes?

**Comment by marbar3778** [comment]
you have to start the rest-server to enable the cosmos routes. this is how you interact with the modules

**Comment by tuckermint** [comment]
it worked! thanks

**Comment by Maksat-luci** [comment]
> it worked! thanks

how to you do it?? Please help, cosmo bro

**Comment by Maksat-luci** [comment]
> you have to start the rest-server to enable the cosmos routes. this is how you interact with the modules
how to you do it?? Please help, cosmo bro

**Comment by tac0turtle** [comment]
in app.toml there is a config for turning on the rest server

**Comment by Maksat-luci** [comment]
> in app.toml there is a config for turning on the rest server

which one ?, I have everything turned on

**Comment by Maksat-luci** [comment]
app-db-backend = ""
halt-height = 0
halt-time = 0
iavl-cache-size = 781250
iavl-disable-fastnode = false
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = "0stake"
pruning = "default"
pruning-interval = "0"
pruning-keep-recent = "0"

[api]
  address = "tcp://0.0.0.0:1317"
  enable = true
  enabled-unsafe-cors = true
  max-open-connections = 1000
  rpc-max-body-bytes = 1000000
  rpc-read-timeout = 10
  rpc-write-timeout = 0
  swagger = true

[grpc]
  address = "0.0.0.0:9090"
  enable = true
  max-recv-msg-size = "10485760"
  max-send-msg-size = "2147483647"

[grpc-web]
  address = "0.0.0.0:9091"
  enable = true
  enable-unsafe-cors = false

[rosetta]
  address = ":8080"
  blockchain = "app"
  denom-to-suggest = "uatom"
  enable = false
  enable-fee-suggestion = false
  gas-to-suggest = 200000
  network = "network"
  offline = false
  retries = 3

[rpc]
  cors_allowed_origins = ["*"]

[state-sync]
  snapshot-interval = 0
  snapshot-keep-recent = 2

[store]
  streamers = []

[streamers]

  [streamers.file]
    keys = ["*"]
    prefix = ""
    write_dir = ""

[telemetry]
  enable-hostname = false
  enable-hostname-label = false
  enable-service-label = false
  enabled = false
  global-labels = []
  prometheus-retention-time = 0
  service-name = ""

[wasm]
  lru_size = 0
  query_gas_limit = 300000

**Comment by tac0turtle** [comment]
did you try restarting your node now?

**Comment by Maksat-luci** [comment]
yes

**Comment by Maksat-luci** [comment]
i dont have url localhost:1317/blocks/latest, but another blockchain has it enabled



> did you try restarting your node now?

mmm how to do this?
build again?

**Comment by Maksat-luci** [comment]
> If you are on v0.46+ the url is: http://localhost:1317/cosmos/base/tendermint/v1beta1/blocks/latest on v0.45 it is http://localhost:1317/blocks/latest
> 
> Which version of the SDK are you using?



46.6

**Comment by Maksat-luci** [comment]
> If you are on v0.46+ the url is: http://localhost:1317/cosmos/base/tendermint/v1beta1/blocks/latest on v0.45 it is http://localhost:1317/blocks/latest
> 
> Which version of the SDK are you using?

how to change version cosmos in created project? or maybe have another exit?

**Comment by Maksat-luci** [comment]
> If you are on v0.46+ the url is: http://localhost:1317/cosmos/base/tendermint/v1beta1/blocks/latest on v0.45 it is http://localhost:1317/blocks/latest
> 
> Which version of the SDK are you using?


thank you i solved that problem
