### ISSUE TITLE
HelloChain Tutorial SecTrustedApplication.h problem with macOS Catalina (10.5.3)

### ISSUE THREAD

**Issue by letterj** [cosmos/sdk-tutorials#247]
Message: 
note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here.

Found a reference to the issue here:   https://github.com/ovrclk/akash/pull/445

I was able to get the project to compile by adding this into the 

go.sum file:
`github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4 h1:/vQbFIOMbk2FiG/kXiLl8BRyzTWDw7gX/Hz7Dd5eDMs=`
`github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4/go.mod h1:hN7oaIRCjzsZ2dE+yG5k+rsdt3qcwykqK6HVGcKwsw4=`

go.mod file:
`replace github.com/keybase/go-keychain => github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4`

After making this modifications I was able to build the project and run the rest of the HelloChain tutorial

**Comment by marbar3778** [comment]
can you post the go.mod file when you had the issue? I can still compile with this warning.

**Comment by letterj** [comment]
Original go.mod and go.sum files
[gomod-gosum.zip](https://github.com/cosmos/sdk-tutorials/files/4210175/gomod-gosum.zip)

**Comment by marbar3778** [comment]
hellochain has been removed, please use the other tutorials 😄
