### ISSUE TITLE
Make install Error

### ISSUE THREAD

**Issue by osiz-blockchainapp** [cosmos/sdk-tutorials#265]
Am getting error in while make install in name service tutorial (https://tutorials.cosmos.network/nameservice/tutorial/00-intro.html).
`github.com/nameservice$ make install
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
go install  -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=NameService -X github.com/cosmos/cosmos-sdk/version.ServerName=nsd -X github.com/cosmos/cosmos-sdk/version.ClientName=nscli -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit= ' ./cmd/nsd
import cycle not allowed
package github.com/cosmos/sdk-tutorials/nameservice/cmd/nsd
	imports github.com/cosmos/sdk-tutorials/nameservice
	imports github.com/cosmos/sdk-tutorials/nameservice/x/nameservice
	imports github.com/cosmos/sdk-tutorials/nameservice/x/nameservice/client/rest
	imports github.com/cosmos/sdk-tutorials/nameservice/x/nameservice
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 1
`

**Comment by marbar3778** [comment]
Could you try pulling master, I just tried to recreate this bug but was not able to

**Comment by osiz-blockchainapp** [comment]
> Could you try pulling master, I just tried to recreate this bug but was not able to

can you say which repository i have to pull

**Comment by marbar3778** [comment]
the sdk-tutorials repo
