### ISSUE TITLE
Nameservice transaction query error

### ISSUE THREAD

**Issue by mustafasevinc** [cosmos/sdk-tutorials#268]
![cosmostxhatası](https://user-images.githubusercontent.com/59833608/75892321-2af87580-5e42-11ea-8606-29d5415ac6dd.png)

When I query Tx in the second node, I get an error. I did everything in tutorial. I have completed the Genesis file and config.toml files. But why didn't it happen?

**Comment by marbar3778** [comment]
are they both reading from the same config files?

**Comment by mustafasevinc** [comment]
No, these are two different vds. 2. I would change this to persistent_peers = "id @ first_node_ip: 26656" in Node's config.toml file.

**Comment by marbar3778** [comment]
the nameservice tutorial underwent refactoring please try again
