### ISSUE TITLE
nameservice: Inconsistencies

### ISSUE THREAD

**Issue by bryanchriswhite** [cosmos/sdk-tutorials#275]
- It looks like the `lvl-1` scaffold template includes a params module now. This is not reflected in the example code.
- Example code imports: "github.com/cosmos/sdk-tutorials/..." vs. "github.com/[user]/[repo]/..."

  The former is used everywhere except for:
  - nameservice/tutorial/09-set-name.md (x/nameservice/handler.go)
  - nameservice/tutorial/12-queriers.md (x/nameservice/internal/keeper/querier.go)
  - nameservice/tutorial/16-rest.md (x/nameservice/client/rest/rest.go)
  
- `nameservice.NewKeeper` argument order seems unconventional, perhaps instead:

  ```go
  app.nsKeeper = nameservice.NewKeeper(
      app.cdc,
      keys[nameservice.StoreKey],
      app.bankKeeper,
      app.subspaces[nameservice.ModuleName],
  )
  ```

  Affected files:
  
  - nameservice/app.go
  - nameservice/tutorials/12-app-complete.md
  - nameservice/tutorials/19-app-complete.md
  - nameservice/x/nameservice/internal/keeper/keeper.go
      
  
- x/nameservice/module.go

  `AppModule#InitGenesis` implementation is inconsistent between the scaffold template and the tutorial.

- nameservice/tutorials/22-build-run.md

  - The first code block in "Running the live network..." section ends abruptly, mid-command, perhaps it should read something like:
      ```
      nsd gentx --name jack --amount 1000000stake
      ```
  
  - "change persistent_peers" doesn't explain that "id" is tendermint node id which I've been obtaining via `nsd tendermint show-node-id`.
      Perhaps there is a more optimal way.

**Comment by hxrts** [comment]
Additionally, the [Keys](https://tutorials.cosmos.network/nameservice/tutorial/04-key.html) section displays a keys.go file that differs from the one built locally. Local version below:

```
package types

const (
	// ModuleName is the name of the module
	ModuleName = "nameservice"

	// StoreKey to be used when creating the KVStore
	StoreKey = ModuleName

  // RouterKey to be used for routing msgs
  RouterKey = ModuleName

  // QuerierRoute to be used for querierer msgs
	QuerierRoute = ModuleName
)
```

Additionally, as I'm pasting this code I notice ModuleName and StoreKey use tab indentation, while RouterKey and QuerierRoute use space indentation.

**Comment by marbar3778** [comment]
Thank you for bringing this items to light. Ill go through the files and correct them, along with going through the entire tutorial as well

**Comment by marbar3778** [comment]
>The first code block in "Running the live network..." section ends abruptly, mid-command, perhaps it should read something like:

There isn't a need to specify the amount. If you don't specify an amount it will default to the hardcoded amount.
