### ISSUE TITLE
setting up go

### ISSUE THREAD

**Issue by hxrts** [cosmos/sdk-tutorials#278]
The linked instructions don't mention anything about a $GOPATH, so could be worthwhile to make sure the go setup is complete by linking to additional instructions or resources.

**Comment by marbar3778** [comment]
what was the issue you were having with GOPATH?

**Comment by hxrts** [comment]
The linked instructions [here](https://golang.org/doc/install) don't mention setting a $GOPATH, presumably because it's being depreciated. However I think proper installation of scaffold requires a I have a $GOPATH set. Not entirely sure, but I think that may be what caused [this issue](https://github.com/cosmos/scaffold/issues/65).

**Comment by harsh-98** [comment]
GOPATH was used in earlier versions of go for defining workspace directory. In the new versions GOPATH is not required. 
`make install` creates the scaffold bin in the default workspace directory. `~/go`.

I think you are getting `scaffold not found` error. For getting rid of this, add `export PATH=$PATH:$HOME/go/bin` to your .bash_profile or .zshrc file.

**Comment by marbar3778** [comment]
will close this issue, thank you for the explanation
