### ISSUE TITLE
The dependency package of some code changes

### ISSUE THREAD

**Issue by Xiaohong027** [cosmos/sdk-tutorials#289]
For instance:

in hellochain/x/greeter/client/cli/tx.go, the version of import cosmos-sdk is v0.38.0. The cosmos-sdk directly cloned is NOT this version. File structure changes.

**Comment by marbar3778** [comment]
hello,

the hellochain tutorial is currently going some refactoring and should not be relied on. Could you please use nameservice or scavenge?
