### ISSUE TITLE
nameservice tutorial remote connection refused

### ISSUE THREAD

**Issue by ilovelili** [cosmos/sdk-tutorials#298]
Hi!

I am new to Cosmos SDK and I just forked the official Cosmos SDK nameservice tutorial. It works well on my local machine so I just deployed it to cloud server and I want to access it thru nscli from localhost.

First I configured nscli to set the node to remote server address on my local machine `nscli config node tcp://{{my remote server ip here}}:26657`

Then I tried to run the following query `nscli query account $(nscli keys show jack -a)`

Finally I got some error like `ERROR: ABCIQuery: Post failed: Post "{{my remote server ip}}:26657": dial tcp : connect: connection refused`

I am curios since I don't think there is any network related problem in my case. Did I mis-configured something?

Thank you very much!
min

**Comment by okwme** [comment]
Hi @ilovelili !
This might be a problem with how your server is configured. It's been a while since I put the nameservice app on a remote server but i found these nginx records from the last time i did:
```nginx
server {
        listen 80;
        listen [::]:80;
        server_name node.talkshop.name;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow_Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

        location / {
                if ($request_method = 'OPTIONS') {
                        add_header 'Access-Control-Max-Age' 1728000;
                        add_header 'Content-Type' 'text/plain charset=UTF-8';
                        add_header 'Content-Length' 0;
                        return 204;
                }
                proxy_redirect off;
                proxy_set_header host $host;
                proxy_set_header X-real-ip $remote_addr;
                proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
                proxy_pass http://localhost:1317;
        }
}


server {
        listen 80;
        listen [::]:80;
        server_name cli.talkshop.name;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow_Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,Cache-Control,Content-Type';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

        location / {
                if ($request_method = 'OPTIONS') {
                        add_header 'Access-Control-Max-Age' 1728000;
                        add_header 'Content-Type' 'text/plain charset=UTF-8';
                        add_header 'Content-Length' 0;
                        return 204;
                }
                proxy_redirect off;
                proxy_set_header host $host;
                proxy_set_header X-real-ip $remote_addr;
                proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
                proxy_pass http://0.0.0.0:26657;
        }
}
```
This was to allow the server to be accessed by the subdomains `cli.talkshop.name` and `node.talkshop.name`. You can see one of them references `0.0.0.0:26657` while the other one references `localhost:1317`, i'm not sure whether those are interchangeable or not. Depending on your server config it might be that you're already exposing those endpoints to the world when you run those processes, or you might need to explicitly expose them with something like an nginx like the one above.

You'll also notice that CORS is enabled in this config. It is disabled by default on the REST server so you need to set it explicitly if it's going to be accessed by a browser directly.

**Comment by ilovelili** [comment]
Hi @okwme !

Thank you very much for your help! You are right that my config file is configured to listen on 127.0.0.1:26657, which should be set to 0.0.0.0:26657 instead.

Thanks again!
min

**Comment by jjhesk** [comment]
here i got this error with 0.0.0.0
`ERROR: ABCIQuery: Post failed: Post "http://0.0.0.0:26657": dial tcp 0.0.0.0:26657: connect: connection refused`

**Comment by jjhesk** [comment]
here i got this error with 0.0.0.0
`ERROR: ABCIQuery: Post failed: Post "http://0.0.0.0:26657": dial tcp 0.0.0.0:26657: connect: connection refused`
