### ISSUE TITLE
Explain how to create genesis file

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/sdk-tutorials#31]
Currently the tutorial hand-waves over Genesis file creation and format. We need to add some more information about this. May bock on https://github.com/cosmos/cosmos-sdk/issues/3006 or https://github.com/cosmos/cosmos-sdk/issues/3406

**Comment by marbar3778** [comment]
genesis file is auto created, I think we need a section in cosmos-sdk docs on how to construct it in app.go. Will close this issue for now

**Comment by 0fatih** [comment]
@tac0turtle Have you guys created a section about it? Because I couldn't see.

If you don't, do you have any suggestions for me? I want to understand the parameters.
