### ISSUE TITLE
next button should be above previous

### ISSUE THREAD

**Issue by hxrts** [cosmos/sdk-tutorials#315]
the default action is for readers to move forward, so this should be how the page is organized

**Comment by marbar3778** [comment]
this is when you are viewing with a smaller screen (mobile) right ?

**Comment by hxrts** [comment]
nope. it's on my laptop ubuntu / firefox 76

![](https://i.imgur.com/12HSGrq.png)

**Comment by marbar3778** [comment]
ah okay, that's odd, want to open a issue here https://github.com/cosmos/vuepress-theme-cosmos
