### ISSUE TITLE
Create a deploy tutorial

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#336]
I've been meaning to do this for a while from the work deploying the persistent name service app, but just a simple tutorial outlining spinning up a digital ocean server, uploading the binary (or building there) and configuring the nginx proxy for a domain name and the port forwarding would be really helpful i think.

**Comment by marbar3778** [comment]
I have been thinking about this. We should have multiple types of tutorials:

- spinning up a validator
- setting up prometheus
- how to use various helper commands
- so on.

**Comment by jjhesk** [comment]
do you have guide for setup a local machine validator to start the demon? @marbar3778

**Comment by barriebyron** [comment]
hi team! are these still goal tutorials? if yes, could you create issues suitable for October Codefest https://blog.cosmos.network/october-codefest-call-for-contributors-42ade37f4913

**Comment by xavierlepretre** [comment]
We have a good approximation with the hands-on-exercise part [running in production](https://github.com/cosmos/sdk-tutorials/blob/4e1b4541218d08b7948cdc46cfa8adc8905a0647/hands-on-exercise/4-run-in-prod/1-run-prod-docker.md). It use Docker Compose.
