### ISSUE TITLE
Note about import appears too late in nameservice tutorial

### ISSUE THREAD

**Issue by loloicci** [cosmos/sdk-tutorials#361]
There is a note about import

> NOTE: Your application needs to import the code you just wrote. Here the import path is set to this repository (github.com/cosmos/sdk-tutorials/nameservice/x/nameservice). If you are following along in your own repo you will need to change the import path to reflect that (github.com/{ .Username }/{ .Project.Repo }/x/nameservice). 

in https://github.com/cosmos/sdk-tutorials/blob/master/nameservice/tutorial/15-cli.md#transactions .

However, the first time an import needs this note appeared is in https://github.com/cosmos/sdk-tutorials/blob/master/nameservice/tutorial/07-keeper.md#keeper-struct .

I suggest moving the note to 07-keeper.md or move it to 07-keeper.md and write short notes to each code need it.
Which sounds better?

**Comment by Tosch110** [comment]
This import is used consistently in the code now. Thanks for creating this Issue.
