### ISSUE TITLE
[Question] Why there is still the comment-outed code using "cliCtx.EnsureAccountExists()" in nameservice?

### ISSUE THREAD

**Issue by loloicci** [cosmos/sdk-tutorials#362]
https://github.com/cosmos/sdk-tutorials/blob/6d737ae233a5e9113082d9bb41424f2f994065f0/nameservice/x/nameservice/client/cli/tx.go#L75-L77

It was comment outed with bf4738a6ee06cbc8eae12eac2e667537cbe8a59c.

Why it is not deleted and still here?
Is the validation implemented in somewhere else used from tx.go?

(Suggestion: I think there should be comments describing the reason aside if it still has some meaning.)

**Comment by Tosch110** [comment]
The commend is removed, thanks for creating this Issue.
