### ISSUE TITLE
Information about "authcmd" in nameservice tutorial is outdated

### ISSUE THREAD

**Issue by loloicci** [cosmos/sdk-tutorials#363]
> The authcmd package is used here. The godocs have more information on usage. It provides access to accounts controlled by the CLI and facilitates signing.

(in https://github.com/cosmos/sdk-tutorials/blob/master/nameservice/tutorial/15-cli.md)

`authcmd` has not been used for a long time.
`authcmd` had used as the alias for github.com/cosmos/cosmos-sdk/x/auth/client/cli. (https://github.com/cosmos/sdk-tutorials/blame/e2eb753fbc2cbe48af6b8aa0831f3952a145fe7b/x/nameservice/client/cli/tx.go#L12)
It should be renewed to the latest information. (But, sorry I don't know about this)

**Comment by marbar3778** [comment]
it has been rewritten to use starport. things should be updated now
