### ISSUE TITLE
Create a go gotchas tutorial

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#374]
* Setting up gopath etc
* Understanding go mod and local development patterns

**Comment by okwme** [comment]
@harmvandendorpel would love to hear what "gotcha"

**Comment by barriebyron** [comment]
I bet @singhhp1069 would be interested in this effort, he is compiling a list of the Go blockers and learning opportunities in his onboarding

**Comment by tmsdkeys** [comment]
Golang tutorial was added: http://tutorials.cosmos.network/tutorials/4-golang-intro/
