### ISSUE TITLE
Unable to buy name using REST API

### ISSUE THREAD

**Issue by dstreppa** [cosmos/sdk-tutorials#377]
Hi all,
I am playing for the first time with the `nameservice` example. Everything works, with the exception of the REST transactions, that I would prefer to use instead of the console `nscli`. Below what happens:

<pre>
$ curl -s http://localhost:1317/auth/accounts/cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw
{
  "height": "705",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw",
      "coins": [
        {
          "denom": "nametoken",
          "amount": "1005"
        }
      ],
      "public_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "A8AlYKCT+1hWqgt/xAG8zlMRYqoXFAqwclqroGZQEz1x"
      },
      "account_number": "3",
      "sequence": "3"
    }
  }
}
$ curl XPOST -s http://localhost:1317/nameservice/names --data-binary '{"base_req":{"from":"cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw","chain_id":"namechain","sequence":"3","account_number":"0"},"name":"siteiwanttobuy.test","amount":"20nametoken","buyer":"cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw"}' && echo
{
  "type": "cosmos-sdk/StdTx",
  "value": {
    "msg": [
      {
        "type": "nameservice/BuyName",
        "value": {
          "name": "siteitryingtobuy.test",
          "bid": [
            {
              "denom": "nametoken",
              "amount": "20"
            }
          ],
          "buyer": "cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw"
        }
      }
    ],
    "fee": {
      "amount": [],
      "gas": "200000"
    },
    "signatures": null,
    "memo": ""
  }
}
$ curl -s http://localhost:1317/auth/accounts/cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw
{
  "height": "721",
  "result": {
    "type": "cosmos-sdk/Account",
    "value": {
      "address": "cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw",
      "coins": [
        {
          "denom": "nametoken",
          "amount": "1005"
        }
      ],
      "public_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "A8AlYKCT+1hWqgt/xAG8zlMRYqoXFAqwclqroGZQEz1x"
      },
      "account_number": "3",
      "sequence": "3"
    }
  }
}
</pre>

As you can see, the returned signature is `null`. Moreover, `nsd` shows that no transactions have been inserted in the chain, confirmed by the second curl reporting the account amount was not changed (1005).
On the other hand, `nscli` output notifies no errors (let's say, I suppose it because the returned status is 100), as shown below:

<pre>
I[2020-08-18|15:55:46.367] Served RPC HTTP response module=rest-server method=GET url=/auth/accounts/cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw status=200 duration=1 remoteAddr=127.0.0.1:43820
I[2020-08-18|15:57:00.146] Served RPC HTTP response module=rest-server method=POST url=/nameservice/names status=200 duration=0 remoteAddr=127.0.0.1:44026
I[2020-08-18|15:57:03.996] Served RPC HTTP response module=rest-server method=GET url=/auth/accounts/cosmos18l5whjqvj55cgj5hr6kvqu4c5n5nk2ryx5a7fw status=200 duration=1 remoteAddr=127.0.0.1:44034
</pre>

Can you help me, please? I am using version `0.37.0-217-g79a0367`.

**Comment by okwme** [comment]
Hi @dstreppa ,
In previous version of the SDK the REST endpoint had the ability to sign transactions. This was considered an insecure key mangement solution and was removed. At this point the REST endpoint can be used for queries and for crafting transactions and submitting already-signed transactions. There CLI is one solution for signing the transactions created by the REST endpoint. Another solution is https://github.com/confio/cosmJS. A previous solution is a signing server that is out of date but could be re-used at https://github.com/jackzampolin/keyserver.

Closing this issue for now, please re-open if I've misunderstood your question.

**Comment by dstreppa** [comment]
Hi @okwme, thank you for the exhaustive answer. OK, now it's clear.

**Comment by dstreppa** [comment]
@okwme https://github.com/confio/cosmJS does not exist anymore. I think the right URL is https://github.com/CosmWasm/cosmjs

**Comment by okwme** [comment]
updated!
