### ISSUE TITLE
Convert nameservice and scavenge to starport-based tutorials

### ISSUE THREAD

**Issue by nylira** [cosmos/sdk-tutorials#378]
I know nobody has bandwidth to work on this yet, but I would love to see these two tutorials updated for Launchpad/Stargate and scaffolded with Starport. 

A marketplace UI for nameservice and a game-style UI for scavenge would be glorious!

**Comment by okwme** [comment]
esp love the marketplace idea!  
I'm presenting at codewithus again soon and was going to update the talkshop.name UI, might be able to include : )

**Comment by Tosch110** [comment]
Both updated to use Starport. Right now version Launchpad.

**Comment by Tosch110** [comment]
Since they are updated and Stargate version is coming soon, maybe create a new Issue for this @nylira ?

`A marketplace UI for nameservice and a game-style UI for scavenge would be glorious!`
