### ISSUE TITLE
[starport tutorials] `frontend` folder has been renamed to `vue`

### ISSUE THREAD

**Issue by nylira** [cosmos/sdk-tutorials#393]
Starport plans on supporting more than just Vue frontends. In v0.0.10, the frontend folder was renamed to vue. Parts of this section needs a find and replace for `frontend` with `vue`.

https://tutorials.cosmos.network/starport-polling-app/#front-end-application

The blog tutorial may need similar updates.

**Comment by lukitsbrian** [comment]
Resolved in #389
