### ISSUE TITLE
Proposal: Integrate some basecoin content in nameservice

### ISSUE THREAD

**Issue by gamarin2** [cosmos/sdk-tutorials#4]
Following up on discussion with jin and @jackzampolin yesterday, and upon further thinking, I think it would be good to integrate content from basecoin that is missing from nameservice. The goal would be to keep nameservice concise while also making it self-sufficient.

Ultimately the question is what is the goal of this tutorial. If we take a look at https://doc.rust-lang.org/, we see there are two things:

- Rust book (https://doc.rust-lang.org/book/2018-edition/index.html). It is described as "Affectionately nicknamed "the book," The Rust Programming Language will give you an overview of the language from first principles. You'll build a few projects along the way, and by the end, you'll have a solid grasp of the language.". 
- Rust by examples: While the book talks about code with a lot of words, RBE shows off a bunch of code, and keeps the talking to a minimum.

If we want nameservice to become this self-sufficient learn by doing example that introduces all the important concepts of the sdk, and I think we agreed it would be, then it ought to be a bit longer and incorporate important explanations that currently live in basecoin. I think this vision for the nameservice example would also be supported by a slight change in narrative described here: https://github.com/cosmos/sdk-module-tutorial/issues/3.

**Comment by jackzampolin** [comment]
I view this tutorial as more of a getting started example. I'm open to including more content here, but I think keeping the getting started experience streamlined and as focused on the code as possible is good. The examples below explain concepts to various levels, but are all focused on getting users to that "WOW" moment (running application that they built) as quickly as possible:

- [Docker](https://docs.docker.com/get-started/#prepare-your-docker-environment)
- [Kubernetes](https://kubernetes.io/docs/tutorials/kubernetes-basics/)
- [Terraform](https://www.terraform.io/intro/getting-started/build.html)
- [Serverless](https://serverless.com/framework/docs/getting-started/)

One thing to note is that all these tutorials also link to deeper explanations in the documentation. I think this prevents people from getting overloaded on project specific concepts while still providing them ready access to all the different documentation they need.

**Comment by marbar3778** [comment]
believe we have decided on how to structure the tutorials, will close this isse
