### ISSUE TITLE
Run REST route to get data on Scavenge return  { "error": "internal"}

### ISSUE THREAD

**Issue by ChatchaiCBV** [cosmos/sdk-tutorials#411]
Refer to the [issue](https://github.com/cosmos/cosmos-sdk/issues/7481). I do the same thing on scavenge tutorial and it shows the same error. Kindly advice how to fix it. Thank you very much.

**Comment by lukitsbrian** [comment]
Which route is returning the error in the scavenge tutorial? 

Note that each tutorial will have different rest routes.

**Comment by ChatchaiCBV** [comment]
I try to GET http://localhost:1317/scavenge/commit/user1 after starting up the scavengeD and scavengeCLI. It returns error as below.

```
{
    "error": "internal"
}
```

**Comment by ChatchaiCBV** [comment]
![image](https://user-images.githubusercontent.com/2574960/95498567-36121600-09ce-11eb-9ae7-4e9db1c784d5.png)

**Comment by lukitsbrian** [comment]
[The `solutionScavengerHash` is being used as the key](https://tutorials.cosmos.network/scavenge/tutorial/09-querier.html) as opposed to the key name (the key name isn't stored in the blockchain itself), which equals `sha256(solution + youraddress)`, so your request should look something like 

```
$ curl http://localhost:1317/scavenge/commit/778ade7bc6277fefda04b37164469f09a5e576f03c25c232694637701d64734f
{
  "height": "0",
  "result": {
    "scavenger": "cosmos1zawyqm2hlj3mlnvtxctaqsklhlyjllczc5awza",
    "solutionHash": "2f9457a6e8fb202f9e10389a143a383106268c460743dd59d723c0f82d9ba906",
    "solutionScavengerHash": "778ade7bc6277fefda04b37164469f09a5e576f03c25c232694637701d64734f"
  }
}
```

I would recommend looking at the script in `./happypath.sh` and take the `solutionScavengerHash` from the `commit-solution` command.

**Comment by ChatchaiCBV** [comment]
Thank you very much for your response. 

In addition, I tried to print out something (fmt.Println("Something")) within keeper querier to recheck that its function was called but it didn't print out in scavengeCLI. I'm not sure keeper querier is called correctly. How can I verify that ?

**Comment by okwme** [comment]
@ChatchaiCBV if you check your running node you should see those print statements (assuming you re-compiled the binary with the new print statement before running it)
