### ISSUE TITLE
Run REST Route return { "error": "internal"}

### ISSUE THREAD

**Issue by ChatchaiCBV** [cosmos/sdk-tutorials#417]
## Summary of Bug

Run REST route to get data from querier but it returns {"error":"internal"}

## Version

cosmos-sdk v0.39.1

## Steps to Reproduce

- I follows the instruction from Nameservice tutorial (https://tutorials.cosmos.network/nameservice/tutorial/21-run-rest.html) to create the REST Routes.
- Start blockchain with Cosmos SDK
- Run GET request from POSTMAN and Cosmos SDK returns {"error":"internal"}

BTW, I clone the sdk-tutorials repository and go into nameservice to run nameservice blockchain. It turns out to return the same error.

- Start nameservice blockchain with Cosmos SDK
```
git clone http://github.com/cosmos/sdk-tutorials
cd sdk-tutorials/nameservice/nameservice
go mod tidy
make install
./init.sh
nameservicecli rest-server --chain-id namechain &
nameserviced start
```
- Run GET request from POSTMAN
```
http://localhost:1317/nameservice/whois/key/resolve
```
- Cosmos SDK returns error.
```
{
    "error": "internal"
}
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lukitsbrian** [comment]
Resolved in #418
