### ISSUE TITLE
Thoughts on the Voter Tutorial

### ISSUE THREAD

**Issue by Joe-mcgee** [cosmos/sdk-tutorials#432]
Hi, just going through the voter tutorial, and I've noticed a couple things that bare mention.

 First it seems ```starport app github.com/joe-mcgee/voter``` scaffolded a slightly different project from the repo.  For example [this](https://github.com/cosmos/sdk-tutorials/blob/master/voter/voter/vue/src/views/Index.vue) popped out as 
```
<template>
  <div>
    <div class="sp-container">
      <sp-sign-in />
      <sp-bank-balances />
      <sp-token-send />
      <!-- this line is used by starport scaffolding # 4 -->
                <sp-type-form type="poll" :fields="['title', 'options', ]" module="voter" />
    </div>
  </div>
</template>

<script>
import * as sp from "@tendermint/vue";

export default {
  components: { ...sp },
};
</script>
```
amongst other differences, not sure where its pulling from.  Anyways, seems like an improvement over the old code for sure, just means that the tutorial instructions that work with Vue can be axed.

This means no specialized UI to add or remove options but https://github.com/cosmos/sdk-tutorials/blob/c16bc8edadc21a33b71b58e0bd9c792a4652ab68/voter/voter/x/voter/client/rest/txPoll.go#L13-L39

can be modified to
```Options []string``` -> ```Options string```
and split out into an array in the logic
```msg := types.NewMsgCreatePoll(creator, req.Title. strings.split(req.Options, " "))```

most certainly not good UI practice, but probably sufficient for such a tutorial

additionally it appears the ```starport type <x> <x_y> <x_z>``` doesn't appear to have just created just `types/MsgCreatePoll` but also `types/SetPoll` and `types/DeletePoll`  which adds some extra conversions of string -> []string.

Cheers,
Taylor
Dev @[Sifchain](https://sifchain.finance/)

**Comment by lukitsbrian** [comment]
Hi @Joe-mcgee, thanks for sharing this.

As we're rapidly iterating and improving Starport, there have been quite a few updates to how the application is scaffolded since this tutorial was created. This includes the additional scaffolding of set/delete operations, as well as moving many of the frontend components to the [tendermint/vue](https://github.com/tendermint/vue) repo.

**Comment by Joe-mcgee** [comment]
Hi @lukitsbrian, anytime

For sure, its looking and feeling good so far, quite excited to see where it goes next
