### ISSUE TITLE
More Scavenge Tutorial fixes

### ISSUE THREAD

**Issue by david-koenig** [cosmos/sdk-tutorials#438]
I just did the tutorial at https://tutorials.cosmos.network/scavenge/tutorial/01-background.html and found it a helpful introduction. Thank you. I noticed some typos and other small issues along the way, and I thought I'd pass them along while they were still fresh in my mind.

1. By far the biggest issue: there are no instructions on how to get the build of scavengecli working when the REST code is broken. It seems to me that both `starport build` and `starport serve` fail without modifying the REST code to be compatible with the changes that are being made in the CLI code. The tutorial makes it seem like the REST code can be ignored. I only got it to build by making meaningless changes in the REST code to eliminate compiler errors.

2. https://tutorials.cosmos.network/scavenge/tutorial/11-play.html: Command `scavengecli q scavenge list` should be `scavengecli q scavenge list-scavenge`

3. https://tutorials.cosmos.network/scavenge/tutorial/07-keeper.html: In keeper/scavenge.go, to be consistent with the other `*Scavenge` functions, I think the last line of `DeleteScavenge` function should be:

`store.Delete([]byte(types.ScavengePrefix + solutionHash))`

**Comment by okwme** [comment]
Thank you for collecting all of these @david-koenig !
We'll try to get them wrapped up asap.
