### ISSUE TITLE
Proof of file existence is broken

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#448]
without following optional instructions to replace `ID` and incrementally fix errors by the time i get to **Submit a Proof of File Existence claim** the app will not compile. The following methods are still missing inside of `/x/pofe/client/cli/tx.go`
 * `GetCmdSetClaim`
 * `GetCmdDeleteClaim`

inside of `/x/pofe/client/cli/txClaim.go` the import statement still make reference to the wrong github user: `"github.com/lukitsbrian/poe/x/pofe/types"` instead of `	"github.com/user/pofe/x/pofe/types"`

**Comment by lukitsbrian** [comment]
Hi @okwme - thanks for pointing this out. It was not the intention for someone to copy/paste the markdown code into `txClaim.go`, rather only import the relevant packages, and update the `GetCmdCreateClaim` function. So `GetCmdSetClaim` and `GetCmdDeleteClaim` should still exist (and be unmodified) - however, I'll elaborate on this more in the tutorial.
