### ISSUE TITLE
Nameservice out of date

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#450]
`key.go` missing `NamePrefix` that is there now with starport

Keeper makes reference to generated `WhoIs` keeper that doesn't exist. Was there a step for using starport with whois?
unclear if the expanded keeper file is supposed to overwrite the contents of `keeper/keeper.go` or go in a new file. if it overwrites then there is missing `NewKeeper`

going to stp here, seems like it's also outdated and would recommend same path forward as scavenge tutorial

**Comment by nikohosn** [comment]
I am also had issues with this tutorial. Seems that it was not updated with the latest release. Are there plans to get this updated anytime soon?

**Comment by Rajakavitha1** [comment]
I am new to Cosmos and I did run into issues when i followed the instructions in the nameservice tutorial:
```
# github.com/Rajakavitha1/nameservice/x/nameservice/client/rest
Error: ../../x/nameservice/client/rest/txWhois.go:78:29: cannot use addr (type "github.com/cosmos/cosmos-sdk/types".AccAddress) as type string in argument to "github.com/Rajakavitha1/nameservice/x/nameservice/types".NewMsgSetName
Error: ../../x/nameservice/client/rest/txWhois.go:78:50: cannot use req.Name (type string) as type "github.com/cosmos/cosmos-sdk/types".AccAddress in argument to "github.com/Rajakavitha1/nameservice/x/nameservice/types".NewMsgSetName
# github.com/Rajakavitha1/nameservice/x/nameservice/client/cli
Error: ../../x/nameservice/client/cli/txWhois.go:55:52: cannot use cliCtx.GetFromAddress() (type "github.com/cosmos/cosmos-sdk/types".AccAddress) as type string in argument to "github.com/Rajakavitha1/nameservice/x/nameservice/types".NewMsgSetName
Error: ../../x/nameservice/client/cli/txWhois.go:55:52: cannot use argsName (type string) as type "github.com/cosmos/cosmos-sdk/types".AccAddress in argument to "github.com/Rajakavitha1/nameservice/x/nameservice/types".NewMsgSetName
Error: Process completed with exit code 2.
```
