### ISSUE TITLE
Ensuring tutorials don't break with updates

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#505]
Currently keeping tutorials up to date with breaking changes in the Cosmos SDK and Stargate is difficult. Breaking changes are not known until a user follows the tutorial and it doesn't work. If we're lucky they report it, then we also need to find the time and capacity to understand and fix the error.

One step better would be to identify when the tutorials break automatically. This could be done by automating the build process of tutorials so that they could be a) run at some regular interval or 2) be attached to some sort of a webhook to be run with new releases for the SDK and starport. The build process would need to essentially emulate the process of a reader, following the instructions provided in the tutorial and run some actual tests at the end to ensure builds and correct behavior. In order to emulate the process of a reader a format needs to be established for a tutorial that can be programatically "followed". 

One option for this would be to rely on code blocks explicitly to be paired with instructions. Each command required is explicit in a code block. Each addition of code to any file needs to be either recognized by line, or the entire file needs to be included. Possibly some combination could be achieved by a "files should look like this" section that accompanies each step of the tutorial.

This option would still require the docs to be updated manually when an error is detected, although we should be able to know right away that's the case (instead of waiting for some poor unsuspecting learner to trigger the alarm for us). Ideally the fix could be potentially included.

This might be possible if the tutorial itself was built programatically by some process—starport for example. Tutorials would need to follow some new programmatic format, some combination of git diffs and namespaced code comments would likely play a useful role. The end result might be that mardown files combinging the code comments with code snippets could be generated by the build instructions to ensure the text is always up to date with the results of the commands.

This is probably a hard problem.

One easier solution would be to enforce strict semver on Starport, so that all breaking changes are MAJOR releases. Another solution would be to make sure the first step of each tutorial had a step to ensure an EXACT version of starport be used. It could look as follows:

> 
> ### Please ensure you have the correct version of Starport installed to guarantee compatibility with this tutorial by running the following command:
> 
> ```
> curl https://i.jpillora.com/tendermint/starport@v0.x.y! | bash
> ```
> 
> Run the following command to make sure the version of your binary matches `v0.x.y`:
> ```
> starport --version
> ```

**Comment by xavierlepretre** [comment]
The content now uses exact versions and relies on package managers to deliver predictable binaries.
