### ISSUE TITLE
Create better chain migration tutorials

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#522]
I added this question to [stackoverflow](https://stackoverflow.com/questions/65874639/what-are-the-steps-to-perform-a-chain-upgrade) because I was having an awful time migrating from a `v0.39` to `v0.39` chain and I couldn't find any information about it. I ended up having to start the chain from scratch and manually adding all the genesis accounts using a bash script.

Made me realize we need a lot more to explain how to do upgrades that aren't about upgrading the SDK, just about updating features of your chain (i may just be clueless and this exists but if that's the case we need to improve the searchability of our docs).

**Comment by Tosch110** [comment]
We do have documentation on migration here: https://docs.cosmos.network/master/migrations/app_and_modules.html

Although after experiencing something similar as you describe, the current procedure we have identified as most promising is actually bootstrapping a new chain with Starport and migrate over the logic to the new chain. 
What do you think about exploring this approach further, than trying to upgrade each module from v0.39 to v0.40? (I think this is what you are looking for?)

**Comment by toschdev** [comment]
Or: How to do a `chain-id` upgrade with exporting genesis and loading a genesis. From start to finish.

**Comment by xavierlepretre** [comment]
Adding features to your chain is now covered with the hands-on-exercise [here](https://github.com/cosmos/sdk-tutorials/blob/4e1b4541218d08b7948cdc46cfa8adc8905a0647/hands-on-exercise/4-run-in-prod/2-migration-info.md). Adding a new module is covered [here](https://github.com/cosmos/sdk-tutorials/blob/4e1b4541218d08b7948cdc46cfa8adc8905a0647/hands-on-exercise/4-run-in-prod/3-add-leaderboard.md).

ATM, there are no tutorials on how to upgrade the underlying Cosmos SDK version.
