### ISSUE TITLE
Have a section for "article tutorials"

### ISSUE THREAD

**Issue by Tosch110** [cosmos/sdk-tutorials#541]
Tutorials that dive deeper into example setups, infrastructure setup or other content that might have a good place in a blog post rather than a module development tutorial.

I would propose we have another section "Articles" like we have "Videos" where we can have a link to certain blog posts.

**Comment by okwme** [comment]
I completely agree!
I think probably we want that section above videos.
We need to be vigilant that the versions keep the articles ever green (just be explicit at the top which versions this is related to)

**Comment by okwme** [comment]
maybe could reuse the articles card format and use the tags to denote more exotic topics like `rust-relayer` or `ibc`

**Comment by okwme** [comment]
we could also use a medium tag and automatically import them like we do in the news section
