### ISSUE TITLE
Blog Tutorial account issue

### ISSUE THREAD

**Issue by ryanli-me** [cosmos/sdk-tutorials#570]
I just ran through the blog tutorial and when I reached this "Launch" step. https://github.com/cosmos/sdk-tutorials/blob/master/blog/tutorial/01-index.md#launch. I found that the command `blogd tx blog create-post "My first post" "This is a post\!" --from=user1` does not work and gives me an error `Error: The specified item could not be found in the keyring`

I checked `~/.blog/keyring-test` and found instead of `user1`, there's `alice`. By replacing `user1` with `alice` everything works. Not sure if this is due to upgrades of Cosmos SDK.

If this is just due to out-of-date tutorial, I'd love to submit a PR fix.

My Env:
CosmosSDK: `v0.41.0`
Starport: `starport version v0.14.0 darwin/amd64 -build date: 2021-02-03T18:53:41Z`

**Comment by ryanli-me** [comment]
Oh, I guess `starport` generates a different `config.yaml`

**Comment by toschdev** [comment]
Yes, this is a change that happened from v0.13.2 to v0.15.0 

I assume you ran the tutorial on latest Starport version and not v0.13.2? 
The tutorial has just been updated to use the latest starport version and should be fine now.
