### ISSUE TITLE
IBC Tutorial Relayer exits prematurely

### ISSUE THREAD

**Issue by ryanli-me** [cosmos/sdk-tutorials#571]
Following the new IBC tutorial, I find that the `relayer` exits with `no transactions returned with query` after sending the ibc transaction. However, the ack was not received on the sender blockchain. After restarting the `relayer`, the ack is received and `list-sentPost` shows the post being sent successfully.

Not sure if this is the expected behavior.

**Comment by tmsdkeys** [comment]
Outdated
