### ISSUE TITLE
create the how the hell series

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#579]
* how the hell does the gov module work?
 * how the hell do i deploy a blockchain
 * how the hell do i use the upgrade module (with and without breaking changes or SDK version bumps)
 * how the hell does the relayer work?
 * how the hell do oracles work?
 * how the hell do i make an NFT that doesn't destroy the environment
 * how the hell do i pay for my users gas?
 * how the hell do i migrate from ethereum?
 *

**Comment by barriebyron** [comment]
@okwme oooh wdyt about this wish list for October Codefest https://blog.cosmos.network/october-codefest-call-for-contributors-42ade37f4913

**Comment by coldice** [comment]
Moved to [https://github.com/cosmos/developer-portal/issues/14](https://github.com/cosmos/developer-portal/issues/14)
