### ISSUE TITLE
move deployment and tutorials build out of README.md  

### ISSUE THREAD

**Issue by barriebyron** [cosmos/sdk-tutorials#602]
I learned how to use the Cosmos SDK tutorial repo today. I wasn't able to learn on my own because the README.md is not available to use for general purpose "what this repo is for" information as expected.
Instead, the README.md file seems to have been hijacked for a non-traditional purpose: layout, build and deployment code for the [Cosmos SDK Tutorials](https://tutorials.cosmos.network/) page.

As we scale up, I'd like to use the README.md for the intended purpose and see the other information move to a more suitable location. Working around this problem by using the Contributing file in https://github.com/cosmos/sdk-tutorials/pull/601 

@okwme to clarify, let's remove the metadata for build and deploy so the README is able to fulfill the actual purpose 

Open to ideas!

**Comment by barriebyron** [comment]
@lovincyrus I remember you saying that you didn't own the metadata in the README 
Do know the history? We're trying to figure out where to move the deploy and build metadata.

**Comment by barriebyron** [comment]
@lukitsbrian is this issue in your court? Or do we need to find a different owner? 
fyi  @toschdev

**Comment by lukitsbrian** [comment]
@barriebyron I think we should leave the metadata as-is for now, as this is something that is used by vuepress to generate the html files.

However, it is still possible to still add text at the bottom of the README with relevant information about the repo.

**Comment by barriebyron** [comment]
@lukitsbrian Yes, I understand. I have two concerns that I want to explore before we give up and leave it as is.
- MAINTENANCE and README purpose
It's not possible to introduce text in all editors. I tried that and when I saved the file it scrunched and flatted all of the metadata (OUCH). It's not good practice IMO.
- ERRORS
Most importantly, having the deploy and build information there presents a risk of introducing errors to the metadata when we update the README. Before we give up, I just wanted to know who is the responsible person and what options we can explore to keep the tutorial builds safe and restrict the README contents to the intended purpose. 

It's working now, but not optimum. Just exploring who and what at this point.

**Comment by barriebyron** [comment]
I made a minor fix to README just now and https://github.com/cosmos/sdk-tutorials/pull/632/commits/f02ddffcf17988b20f1222d93377af087f871c1b 
happened... just seems too easy to smurch our build (that's a technical term: smurch)

**Comment by barriebyron** [comment]
@marbar3778 can you help us determine how we can move the metadata for build and deploy out of README and into a new file, like DEPLOY.md 
@toschdev

**Comment by coldice** [comment]
Moved to https://github.com/cosmos/developer-portal/issues/15
