### ISSUE TITLE
Get instant feedback from the tutorials page

### ISSUE THREAD

**Issue by toschdev** [cosmos/sdk-tutorials#610]
It would be nice to have a form on the tutorials page that pops up at the middle / end of the tutorial that asks for feedback what might be missing / what was hard to understand or could be improved on tutorials.

We need feedback to improve in the direction where users are still struggling with concepts

**Comment by xavierlepretre** [comment]
Now each page has at the bottom: 🙂😐🙁 and free-form text field.
