### ISSUE TITLE
Install Starport link does not work on some of the tutorials

### ISSUE THREAD

**Issue by shahbazn** [cosmos/sdk-tutorials#625]
Install startport link returns 404 for some of the tutorials e.g. here https://github.com/cosmos/sdk-tutorials/blob/master/hello-world/tutorial/index.md#prerequisites

**Comment by barriebyron** [comment]
thanks @shahbazn Thanks for letting us know about the dreaded 404. If you're up for making direct contributions with a PR, the best way is to fork the repo and submit a PR against master. Pinging you now.

**Comment by barriebyron** [comment]
thanks @shahbazn for the quick fix
