### ISSUE TITLE
feedback: provide a tutorial without starport

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/sdk-tutorials#637]
Some feedback from teams going through the tutorials is starport does too much magic. They would like to create a module from scratch. This tutorial can be a more advanced tutorial of an existing tutorial. This will bridge teams that don't use starport and ones that do. 

Also if I have a repo that does not use starport, can I use starport to scaffold a module?

**Comment by xavierlepretre** [comment]
Such a tutorial is on the roadmap but without any ETA.
