### ISSUE TITLE
Connecting to testnet: add a section on how to send tokens with TS

### ISSUE THREAD

**Issue by fadeev** [cosmos/sdk-tutorials#658]
- [ ] Clone the repo: `git clone --branch v1.0.1 https://github.com/b-harvest/gravity-dex`
- [ ] Install Starport `develop`
- [ ] Add `client.vuex.path: "client"` to config
- [ ] Run `starport serve --reset --rebuild-proto-once` to generate libraries
- [ ] Request tokens from the faucet using `curl`
- [ ] Create a TS project with `npm`, install dependencies
- [ ] Write an example on how to send tokens using the generated TS lib (sort of like [cosmjs example](https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9#send-your-first-stargate-transaction-from-javascript))

Related PR: https://github.com/cosmos/sdk-tutorials/pull/657

**Comment by xavierlepretre** [comment]
The Typescript part is covered with CosmJS [here](https://github.com/cosmos/sdk-tutorials/blob/4e1b4541218d08b7948cdc46cfa8adc8905a0647/tutorials/7-cosmjs/2-first-steps.md).
