### ISSUE TITLE
Voter tutorial missing test modification

### ISSUE THREAD

**Issue by jclyons52** [cosmos/sdk-tutorials#681]
after the 0.16 star port update the tutorial does not show how to correctly mock the bankKeeper in the new tests keeper_test.go. The file expected_keepers.go also no longer exists.

**Comment by jclyons52** [comment]
my solution was to add https://github.com/golang/mock and generate mocks with `mockgen -source=x/voter/types/types.go > x/voter/mock_types/mocks.go` having put the BankKeeper in the types.go file. usage
`
func setupKeeper(t testing.TB) (*Keeper, sdk.Context) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	bankKeeper := mocks.NewMockBankKeeper(ctrl)
	...
	keeper := NewKeeper(codec.NewProtoCodec(registry), storeKey, memStoreKey, bankKeeper)
}
`

**Comment by lubtd** [comment]
Hey @jclyons52, the Voter tutorial still requires Starport `0.15.1`: https://tutorials.cosmos.network/voter/#requirements

Thanks for the issue, it mays help updating the tutorial for supporting Starport `0.16.0`

**Comment by xavierlepretre** [comment]
It looks like this refers to obsolete content.
