### ISSUE TITLE
Interchain Exchange: buy/sell order

### ISSUE THREAD

**Issue by fadeev** [cosmos/sdk-tutorials#697]
> In the interchain-exchange tutorial at the Buy Orders section: https://tutorials.cosmos.network/interchain-exchange/tutorial/07-buy-orders.html

> the pre-transmit section is copied over from the Sell Order section, thus it describes the pre-transmit package checks for a sell order not a buy order.

![Screenshot_from_2021-06-12_22-16-40](https://user-images.githubusercontent.com/332151/121795339-32075980-cc29-11eb-8de6-4fb29ebc2279.jpg)

![Screenshot_from_2021-06-12_22-29-39](https://user-images.githubusercontent.com/332151/121795340-3469b380-cc29-11eb-820e-4739b08887c1.png)

**Comment by lubtd** [comment]
There is actually a mistake with `sell order` that must be changed to `buy order`, good catch.

However, you also have token burn when sending a buy order since you send the amount of price to the module. Though, maybe we should precise this is the price a a different token from the sell order

**Comment by xavierlepretre** [comment]
@murataniloener Is this something that would be worth adding to future revisions of the content?
