### ISSUE TITLE
Add nsdebug to cmd and makefile

### ISSUE THREAD

**Issue by gamarin2** [cosmos/sdk-tutorials#72]
Just like `gaiadebug`. It would be nice so that people can query txs bytes from tendermint rpc and then unmarshall them to JSON.

**Comment by jackzampolin** [comment]
I think this is best as a piece of `gaiacli`. We should move the commands from `gaiadebug` to `gaiacli debug`

**Comment by marbar3778** [comment]
this has been added to gaiad, but we have to wait for 0.38 to be released to get the feature.
