### ISSUE TITLE
Broken link "Chat with Cosmos developers in Discord" in tutorial page footer 

### ISSUE THREAD

**Issue by ekkis** [cosmos/sdk-tutorials#815]
**What tutorial are you working in?**
https://tutorials.cosmos.network/liquidity-module/

**Describe the bug**
at the bottom of the page there is a section called "Questions?" that contains a link to the Discord server.  when I click on the link I get the error message: "Invite Invalid" with the explanation: "The invite may be expired or you may not have permission to join"

**To reproduce**
1. visit the tutorial
2. click on the Discord link

**Solution**
I don't know how to fix it.  I reached out to the Discord team and they indicated I needed to reach out to the project directly for a solution

**Comment by barriebyron** [comment]
thanks @ekkis this link has now been replaced by an evergreen link 
thanks to @soniasingla for taking this action!
