### ISSUE TITLE
Unable to start a Node on testnet - seeds not connecting

### ISSUE THREAD

**Issue by pratikasr** [cosmos/sdk-tutorials#825]
**What tutorial are you working in?**
https://tutorials.cosmos.network/connecting-to-testnet/building-binary.html

**Describe the bug**
Whenever I try to run the testnet using the above-mentioned steps an error shows up - couldn't connect to any seeds.

**To reproduce**
Steps to reproduce the behaviour:
1. trying to run the node on testnet

**Include the output of these commands**

ERR Error dialing seed err="dial tcp 34.139.180.212:31729: connect: connection refused" module=p2p seed={"id":"e6fab0296c0cc31228756822b15e98cfa84ff97b","ip":"34.139.180.212","port":31729}
ERR Error dialing seed err="dial tcp 34.139.133.217:32073: connect: connection refused" module=p2p seed={"id":"64fefc98915aa430417ba893bf13bd8cc101aedf","ip":"34.139.133.217","port":32073}
ERR Couldn't connect to any seeds module=p2p

**Comment by xavierlepretre** [comment]
It looks like this is referring to obsolete content.
