### ISSUE TITLE
docs out of date

### ISSUE THREAD

**Issue by okwme** [cosmos/sdk-tutorials#828]
**What tutorial are you working in?**

https://tutorials.cosmos.network/connecting-to-testnet/using-cli.html#querying-balances

this page was reported as being out of date

**Describe the bug**
Tell us about your challenges. A clear and concise description of your problem helps us reproduce the issue. 

**To reproduce**

**Include the output of these commands**
 - If you are using Starport: `starport version`
 - `go version`
 - `uname -a`

**Solution**
Do you have a solution? See [CONTRIBUTING.md](https://github.com/cosmos/sdk-tutorials/blob/master/CONTRIBUTING.md) and feel free to submit a PR.

**Comment by julienrbrt** [comment]
I don't think this is still relevant.
