### ISSUE TITLE
docs: create tutorial for Cosmos SDK events from existing content

### ISSUE THREAD

**Issue by barriebyron** [cosmos/sdk-tutorials#841]
**Is your feature request related to a problem? Please describe.**
The current Cosmos SDK docs provide a conceptual overview of events https://docs.cosmos.network/master/core/events.html 

However, a tutorial does not exist.

A contributor can use this content from Ethan Frey, founder of CosmWasm. @okwme recommends this content as one of the most in-depth articles on events. 

We think this content is a good candidate for an easy article to add to [https://tutorials.cosmos.network/](https://tutorials.cosmos.network/). 

**Describe the solution you'd like to see**

Turn this content into a tutorial with a user journey to help Cosmos SDK users understand events.

- Review and understand this technical content to work from: https://github.com/CosmWasm/wasmd/blob/master/EVENTS.md
- Create a new Markdown file using the https://github.com/cosmos/sdk-tutorials/blob/master/templates/tutorial_template.md 

Resources:
- https://github.com/cosmos/sdk-tutorials/ 

Writing questions? See the excellent advice in the Google developer documentation style guide
- https://developers.google.com/style

Happy hacking!

**Comment by xavierlepretre** [comment]
The hands-on-exercise now demonstrate how to [emit events](https://github.com/cosmos/sdk-tutorials/blob/master/hands-on-exercise/1-ignite-cli/7-events.md) and how to [listen to them](https://github.com/cosmos/sdk-tutorials/blob/master/hands-on-exercise/3-cosmjs-adv/5-server-side.md) with CosmJS.
