### ISSUE TITLE
undefined Methods: MustMarshalBinaryBare & MustUnmarshalBinaryBare

### ISSUE THREAD

**Issue by danburck** [cosmos/sdk-tutorials#843]
**What tutorial are you working in?**
https://tutorials.cosmos.network/blog/tutorial/01-index.html#add-the-post-keeper

**Describe the bug**
The methods `MustMarshalBinaryBare` and `MustUnmarshalBinaryBare` seem to be undefined for `k.cdc`

**To reproduce**
Follow the instructions for Add Post Keeper. 

**Include the output of these commands**
 - If you are using Starport: `starport version`
 - `go version`
 - `uname -a`

**Solution**
Use `MustMarshal` and `MustUnmarshal` instead

**Comment by jianchengwang** [comment]
the same issue

**Comment by jianchengwang** [comment]
> **What tutorial are you working in?** https://tutorials.cosmos.network/blog/tutorial/01-index.html#add-the-post-keeper
> 
> **Describe the bug** The methods `MustMarshalBinaryBare` and `MustUnmarshalBinaryBare` seem to be undefined for `k.cdc`
> 
> **To reproduce** Follow the instructions for Add Post Keeper.
> 
> **Include the output of these commands**
> 
> * If you are using Starport: `starport version`
> * `go version`
> * `uname -a`
> 
> **Solution** Use `MustMarshal` and `MustUnmarshal` instead

the cosmos SDK tutorials based on startport v0.16.2, and latest is v0.18.3,so check your startport version first.

**Comment by xavierlepretre** [comment]
It looks like this is referring to obsolete content.
