### ISSUE TITLE
bug: Documentation link on home page to IBC docs is 404 

### ISSUE THREAD

**Issue by barriebyron** [cosmos/sdk-tutorials#865]
**What is the specific Developer Portal page?**
https://developers.cosmos.network/

**Describe the bug**
The IBC protocol Documentation link at the bottom of the page results in a 404

![image](https://user-images.githubusercontent.com/10067215/142062150-33e1fce0-5796-4b82-90d6-64014200a496.png)

**Solution**
change
https://github.com/cosmos/ics/tree/master/ibc 
to
https://docs.cosmos.network/master/ibc/overview.html

**Comment by barriebyron** [comment]
suggest that you also add a link to the Starport docs 

docs.starport.com

**Comment by nooomski** [comment]
When I click the link here it leads to https://ibc.cosmos.network/
Maybe try cleaning your cache.

Agreed on starport docs!

**Comment by barriebyron** [comment]
lightning fast fix!
