### ISSUE TITLE
Commas

### ISSUE THREAD

**Issue by neneboe** [cosmos/sdk-tutorials#953]
I'm reading through the Cosmos Academy, starting from the beginning (https://tutorials.cosmos.network/academy/0-welcome/), and I noticed there are several commas missing on many of the pages. Some of them are stylistic (like series commas), but other spots should probably have them, like separating prepositional phrases or independent clauses. I'd be happy to make corrections as I read through the material and make a PR. I just wanted to confirm this wasn't an intentional style choice first.

**Comment by barriebyron** [comment]
Hi, @neneboe, we love commas! Your feedback is welcome and so are your direct contributions.

See https://github.com/cosmos/sdk-tutorials/blob/master/CONTRIBUTING.md for guidelines on how to get started with updates.

I look forward to your PRs with fixes. 

About style choice: comma abuse is unintentional, this Cosmos Academy is brand new so we have a few rough edges to smooth out. We're so glad you are willing to help make updates to help improve our technical content.
