### ISSUE TITLE
text still says "Build a chain in hours" change to minutes

### ISSUE THREAD

**Issue by barriebyron** [cosmos/sdk-tutorials#955]
**What is the specific Developer Portal page?**

https://tutorials.cosmos.network/

**Describe the bug**

text says "Build a chain in hours"

![image](https://user-images.githubusercontent.com/10067215/148073696-199df0b0-9074-4b40-8cc6-e9eb3caed347.png)

**Solution**

Change text to say "Build a chain in minutes"

**Comment by nooomski** [comment]
Ah yeah, that'll be [this pr](https://github.com/cosmos/sdk-tutorials/pull/922). Can we merge @coldice ?
